import{a as v,S as b,i as u}from"./assets/vendor-63518809.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(r){if(r.ep)return;r.ep=!0;const n=s(r);fetch(r.href,n)}})();const a=document.querySelector(".mobile-menu-btn"),l=document.querySelector(".menu-wrapper"),S=document.querySelector(".page-nav-button");S.addEventListener("click",()=>{const e=a.getAttribute("aria-expanded")==="true";a.setAttribute("aria-expanded",!e),l.classList.toggle("is-open")});a.addEventListener("click",()=>{const e=a.getAttribute("aria-expanded")==="true";a.setAttribute("aria-expanded",!e),l.classList.toggle("is-open")});const q=document.querySelector(".menu-button-close");q.addEventListener("click",()=>{a.setAttribute("aria-expanded","false"),l.classList.remove("is-open")});const E=document.querySelectorAll(".menu-nav-list-item a");E.forEach(e=>{e.addEventListener("click",()=>{a.setAttribute("aria-expanded","false"),l.classList.remove("is-open")})});async function x(){const e="https://portfolio-js.b.goit.study/api/reviews";return(await v.get(e)).data}async function A(e){const t="https://portfolio-js.b.goit.study/api/requests",s=await v.post(t,e);return console.log(s),s.data}const f=document.querySelector(".swiper-arrow-left"),g=document.querySelector(".swiper-arrow-right"),k=function(e,t=1){new b(e,{breakpoints:{768:{slidesPerView:2},1440:{slidesPerView:4}},spaceBetween:16,cssMode:!0,navigation:{nextEl:".swiper-button-right",prevEl:".swiper-button-left"},pagination:{el:".swiper-pagination"},on:{init:function(){h(this),w(this)},slideChange:function(){h(this),w(this)}},mousewheel:!0,keyboard:!0})};function h(e){e.activeIndex===0?f.setAttribute("src","./img/arrow-left-disabled.svg"):f.setAttribute("src","./img/arrow-left.svg")}function w(e){const t=e.slides.length;e.activeIndex===t-1?g.setAttribute("src","./img/arrow-right-disabled.svg"):g.setAttribute("src","./img/arrow-right.svg")}document.querySelector(".mySwiper");const M=async()=>{try{const t=(await x()).map(({avatar_url:r,author:n,review:i})=>({avatar_url:r,author:n,review:i})),s=document.querySelector(".swiper-wrapper"),o=t.map(({_id:r,author:n,avatar_url:i,review:L})=>`<div class="swiper-slide card">
    <img
    loading="lazy"
      class="card-image"
      src="${i}"
      alt="${n}" 
    />
    <h4 class="card-author">${n}</h4>
    <p class="card-review">${L}</p>
</div>`).join("");s.insertAdjacentHTML("beforeend",o)}catch{u.error({title:"Error",message:"Not found",position:"topRight"});return}};window.addEventListener("DOMContentLoaded",()=>{M(),k(".mySwiper")});const d=document.querySelector(".form-work-together"),m=document.querySelector(".modal-text-box"),p=document.querySelector("[data-modal]"),O=document.querySelector("[data-modal-close]");let c={};d.elements.email.addEventListener("input",B);function B(e){const t=e.currentTarget.value.trim();c.email=t}d.elements.comments.addEventListener("input",C);function C(e){const t=e.currentTarget.value.trim();c.comment=t}d.addEventListener("submit",H);function H(e){if(e.preventDefault(),c.email){if(!c.comment){u.show({position:"topRight",color:"red",messageColor:"black",message:"Fill in the comments field, please"});return}}else{u.show({position:"topRight",color:"red",messageColor:"black",message:"Fill in the email field, please"});return}A(c).then(t=>{p.classList.remove("is-hidden");const s=P(t);m.innerHTML=s}),d.reset()}function P({message:e,title:t}){return`
        <h3 class="modal-title">
          ${t}
        </h3>
        <p class="modal-text">
          ${e}
        </p>
    `}O.addEventListener("click",y);document.addEventListener("click",y);document.addEventListener("keydown",R);function R(e){e.key==="Escape"&&(p.classList.add("is-hidden"),m.innerHTML="")}function y(){p.classList.add("is-hidden"),m.innerHTML=""}document.addEventListener("DOMContentLoaded",function(){document.querySelectorAll(".faq").forEach(t=>{const s=t.querySelector(".faq-question-container"),o=t.querySelector(".faq-answer-container"),r=s.querySelector(".faq-list-btn");s.addEventListener("click",function(){t.classList.toggle("active"),o.style.maxHeight?(o.style.maxHeight=null,r.classList.remove("rotated")):(o.style.maxHeight=o.scrollHeight+"px",r.classList.add("rotated"))})})});
//# sourceMappingURL=commonHelpers.js.map
