import{a as d,S as p,i as l}from"./assets/vendor-87fbb236.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();async function m(){const r="https://portfolio-js.b.goit.study/api/reviews";return(await d.get(r)).data}async function f(r){const o="https://portfolio-js.b.goit.study/api/requests",i=await d.post(o,r);return console.log(i),i.data}const w=function(r,o=1){new p(r,{slidesPerView:o,breakpoints:{768:{slidesPerView:2},1440:{slidesPerView:4}},spaceBetween:16,cssMode:!0,navigation:{nextEl:".swiper-button-right",prevEl:".swiper-button-left"},pagination:{el:".swiper-pagination"},mousewheel:!0,keyboard:!0})};document.querySelector(".mySwiper");const g=async()=>{try{const o=(await m()).map(({avatar_url:e,author:t,review:s})=>({avatar_url:e,author:t,review:s})),i=document.querySelector(".swiper-wrapper"),a=o.map(({_id:e,author:t,avatar_url:s,review:u})=>`<div class="swiper-slide card">
    <img
    loading="lazy"
      class="card-image"
      src="${s}"
      alt="${t}" 
    />
    <h4 class="card-author">${t}</h4>
    <p class="card-review">${u}</p>
</div>`).join("");i.insertAdjacentHTML("beforeend",a)}catch{l.error({title:"Error",message:"Not found",position:"topRight"});return}};window.addEventListener("DOMContentLoaded",()=>{g(),w(".swiper")});const c=document.querySelector(".form-work-together");let n={};c.elements.email.addEventListener("input",h);function h(r){const o=r.currentTarget.value.trim();n.email=o}c.elements.comments.addEventListener("input",y);function y(r){const o=r.currentTarget.value.trim();n.comment=o}c.addEventListener("submit",v);function v(r){if(r.preventDefault(),n.email){if(!n.comment){l.show({position:"topRight",color:"red",messageColor:"black",message:"Fill in the comments field, please"});return}}else{l.show({position:"topRight",color:"red",messageColor:"black",message:"Fill in the email field, please"});return}f(n),c.reset()}
//# sourceMappingURL=commonHelpers.js.map
